name: Deploy Main
on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.12"

jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Twine and Build
        run: sudo pip install twine build

      - name: Create the distribution
        run: |
          git fetch --prune --unshallow --tags
          sudo python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1