name: Test Build

on:
  pull_request:
    branches: [main]
jobs:
  build-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Twine and Build
        run: sudo pip install twine build

      - name: Create the distribution
        run: |
          git fetch --prune --unshallow --tags
          sudo python3 -m build
